# Generated by Django 3.2 on 2021-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.IntegerField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('game_state', models.JSONField()),
            ],
        ),
    ]
