# Generated by Django 3.2 on 2021-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.TextField(choices=[('GATH', 'Gathering players'), ('PLAY', 'Playing'), ('DONE', 'Finished')], default='GATH', max_length=4)),
                ('state', models.JSONField()),
            ],
        ),
    ]
