# Generated by Django 3.2 on 2021-04-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamestate',
            old_name='game_state',
            new_name='state',
        ),
    ]
