# Generated by Django 3.2 on 2021-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='state',
            new_name='components',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
