# Generated by Django 3.2 on 2021-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_game_state_gamestate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='status',
            field=models.TextField(choices=[('GATH', 'Gathering players'), ('PLAY', 'Playing'), ('DONE', 'Finished')], default='GATH', max_length=4),
        ),
    ]
